### ISSUE TITLE
Does not compile for kernel 5.4 on Kubuntu 18.04

### ISSUE THREAD

**Issue by sashamishchenko** [tomaspinho/rtl8821ce#95]
Hello!
Failed to compile module for kernel 5.4.0-050400rc5-lowlatency from https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.4-rc5/
Used last version of module from git for today

1 issue:
#make -C /lib/modules/5.4.0-050400rc5-lowlatency/build M=/home/asm/rtl8821ce/rtl8821ce clean
cd hal ; rm -fr */*/*/*.mod.c */*/*/*.mod */*/*/*.o */*/*/.*.cmd */*/*/*.ko
cd hal ; rm -fr */*/*.mod.c */*/*.mod */*/*.o */*/.*.cmd */*/*.ko
cd hal ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd core ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep/linux ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd platform ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
rm -fr Module.symvers ; rm -fr Module.markers ; rm -fr modules.order
rm -fr *.mod.c *.mod *.o .*.cmd *.ko *~
rm -fr .tmp_versions
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.4.0-050400rc5-lowlatency/build M=/home/asm/rtl8821ce/rtl8821ce  modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-050400rc5-lowlatency'
/home/asm/rtl8821ce/rtl8821ce/Makefile:2162: //hal/phydm/phydm.mk: No such file or directory
/home/asm/rtl8821ce/rtl8821ce/Makefile:2171: //rtl8821c.mk: No such file or directory
make[2]: *** No rule to make target '//rtl8821c.mk'.  Stop.
Makefile:1649: recipe for target '/home/asm/rtl8821ce/rtl8821ce' failed
make[1]: *** [/home/asm/rtl8821ce/rtl8821ce] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-050400rc5-lowlatency'
Makefile:2242: recipe for target 'modules' failed
make: *** [modules] Error 2
ERROR

If I add TopDIR = /home/asm/rtl8821ce/rtl8821ce then it start to compile.

2. But does not finish compilation.
...
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^~~~~~~~~~
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^~~~~~~~~~
./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^~~~~~~~~~~~
./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
   __WARN();      \
   ^~~~~~
/home/asm/rtl8821ce/rtl8821ce/include/osdep_service.h:473:32: note: in expansion of macro ‘WARN_ON’
 #define rtw_warn_on(condition) WARN_ON(condition)
                                ^~~~~~~
/home/asm/rtl8821ce/rtl8821ce/core/rtw_mlme_ext.c:15968:3: note: in expansion of macro ‘rtw_warn_on’
   rtw_warn_on(1);
   ^
scripts/Makefile.build:265: recipe for target '/home/asm/rtl8821ce/rtl8821ce/core/rtw_mlme_ext.o' failed
make[2]: *** [/home/asm/rtl8821ce/rtl8821ce/core/rtw_mlme_ext.o] Error 1
Makefile:1649: recipe for target '/home/asm/rtl8821ce/rtl8821ce' failed
make[1]: *** [/home/asm/rtl8821ce/rtl8821ce] Error 2
make[1]: Залишаю каталог "/usr/src/linux-headers-5.4.0-050400rc5-lowlatency"
Makefile:2243: recipe for target 'modules' failed
make: *** [modules] Error 2
ERROR

**Comment by sashamishchenko** [comment]
sudo ./dkms-install.sh
[make.log](https://github.com/tomaspinho/rtl8821ce/files/3794514/make.log)
About to run dkms install steps...
Error! DKMS tree already contains: rtl8821ce-v5.5.2_34066.20190614
You cannot add the same module/version combo more than once.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.4.0-050400rc5-lowlatency...(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8821ce: v5.5.2_34066.20190614 not found
Error! Bad return status for module build on kernel: 5.4.0-050400rc5-lowlatency (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.4.0-050400rc5-lowlatency...(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8821ce: v5.5.2_34066.20190614 not found
Error! Bad return status for module build on kernel: 5.4.0-050400rc5-lowlatency (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.
Finished running dkms install steps.

**Comment by alanfox2000** [comment]
New Driver Release from Realtek FTP Server

Mirrors:
Part1: https://github.com/alanfox2000/realtek-linux/blob/master/RTL8821CE/RTL8821CE_WiFi_linux_v5.5.2.1_35598_COEX20180712-3232.20191029.part1.rar
Part2: https://github.com/alanfox2000/realtek-linux/blob/master/RTL8821CE/RTL8821CE_WiFi_linux_v5.5.2.1_35598_COEX20180712-3232.20191029.part2.rar

**Comment by Electrocze** [comment]
@alanfox2000 Hi , how can i install this driver please?

**Comment by sashamishchenko** [comment]
I've got errors by compile drivers from Realtek FTP site on Kubuntu 18.04 with kernel 5.4...
I have used part1 archive. Why are exist 2 parts?

**Comment by tomaspinho** [comment]
Have you managed to install it again?

**Comment by sashamishchenko** [comment]
have tested from this git on 5.4.1 ubuntu kernel and got next:
...
/home/asm/rtl8821ce/rtl8821ce/core/rtw_mlme_ext.c:15968:3: note: in expansion of macro ‘rtw_warn_on’
   rtw_warn_on(1);
   ^
In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/thread_info.h:12,
                 from ./arch/x86/include/asm/preempt.h:7,
                 from ./include/linux/preempt.h:78,
                 from ./include/linux/spinlock.h:51,
                 from ./include/linux/seqlock.h:36,
                 from ./include/linux/time.h:6,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:10,
                 from /home/asm/rtl8821ce/rtl8821ce/include/basic_types.h:76,
                 from /home/asm/rtl8821ce/rtl8821ce/include/drv_types.h:26,
                 from /home/asm/rtl8821ce/rtl8821ce/core/rtw_mlme_ext.c:17:
./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^~~~~~~~~~
...

**Comment by skbkrish** [comment]
doesn't work for kernel 5.4.2-1-MANJARO either.

**Comment by skoch98** [comment]
> doesn't work for kernel 5.4.2-1-MANJARO either.

With Manjaro I was able to solve it like this:
 - `sudo ./dkms-remove.sh`
 - `sudo pacman -S linux54-headers`
 - `sudo ./dkms-install.sh`

**Comment by paulovieira** [comment]
If it helps: I'm using Kubuntu 18.04.3 with kernel 5.0.0-37-generic, and everything works well.

**Comment by sashamishchenko** [comment]
> If it helps: I'm using Kubuntu 18.04.3 with kernel 5.0.0-37-generic
Yes. It works fine with 5.0.0.*
But I want use kernel 5.4(it has improvements for my hardware)

**Comment by tomaspinho** [comment]
Is this not a duplicate of https://github.com/tomaspinho/rtl8821ce/issues/112 ?

**Comment by sashamishchenko** [comment]
Yes! It helps!
Have checked on 5.4.10.
Will check it on next kernels too...

**Comment by sashamishchenko** [comment]
It has compiled and works, but does not work link signal leveling in Network Manager on KDE5, like it was earlier(https://github.com/tomaspinho/rtl8821ce/issues/40).

**Comment by sashamishchenko** [comment]
Kernel 5.5.0-050500rc5-lowlatency compiled and works like 5.4.10. Wi-Fi available, but signal level indication does not work.

**Comment by skbkrish** [comment]
the #112 solution doesn't work for linux 5.4.13-MANJARO. Still a bad exit status upon ./dkms-install.sh
