### ISSUE TITLE
Deprecated feature CLEAN

### ISSUE THREAD

**Issue by walrus543** [tomaspinho/rtl8821ce#361]
Hi,
I noticed this message when upgrading to 6.14.4 using Arch Linux.
````
==> dkms install --no-depmod rtl8821ce/1.0.5.r178.g98cff1d -k 6.14.4-arch1-1
Deprecated feature: CLEAN (/var/lib/dkms/rtl8821ce/1.0.5.r178.g98cff1d/source/dkms.conf)
````

Regards.

**Comment by Gemini04126** [comment]
I saw this myself, and also got this after;
```
Error! Bad return status for module build on kernel: 6.17.0-arch1-1 (x86_64)
Consult /var/lib/dkms/rtl8821ce/1.0.5.r186.g5df613d/build/make.log for more information.
==> WARNING: `dkms install --no-depmod rtl8821ce/1.0.5.r186.g5df613d -k 6.17.0-arch1-1' exited 10
```
I had to un-blacklist the default drivers to even connect to the internet, because the module wasn't installed properly.

EDIT:
Here's the part of the build log where it found errors;
```
os_dep/linux/ioctl_cfg80211.c:9618:29: error: initialization of ‘int (*)(struct wiphy *, int,  u32)’ {aka ‘int (*)(struct wiphy *, int,  unsigned int)’} from incompatible pointer type ‘int (*)(struct wiphy *, u32)’ {aka ‘int (*)(struct wiphy *, unsigned int)’} [-Wincompatible-pointer-types]
 9618 |         .set_wiphy_params = cfg80211_rtw_set_wiphy_params,
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9618:29: note: (near initialization for ‘rtw_cfg80211_ops.set_wiphy_params’)
os_dep/linux/ioctl_cfg80211.c:3209:12: note: ‘cfg80211_rtw_set_wiphy_params’ declared here
 3209 | static int cfg80211_rtw_set_wiphy_params(struct wiphy *wiphy, u32 changed)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9623:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, int,  enum nl80211_tx_power_setting,  int)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, enum nl80211_tx_power_setting,  int)’ [-Wincompatible-pointer-types]
 9623 |         .set_tx_power = cfg80211_rtw_set_txpower,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9623:25: note: (near initialization for ‘rtw_cfg80211_ops.set_tx_power’)
os_dep/linux/ioctl_cfg80211.c:4052:12: note: ‘cfg80211_rtw_set_txpower’ declared here
 4052 | static int cfg80211_rtw_set_txpower(struct wiphy *wiphy,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9624:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, int,  unsigned int,  int *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, unsigned int,  int *)’ [-Wincompatible-pointer-types]
 9624 |         .get_tx_power = cfg80211_rtw_get_txpower,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by chim20air** [comment]
I have the same issue. I am attaching the log file which has the same errors that had been exposed by @Gemini04126 

[make.log](https://github.com/user-attachments/files/22756370/make.log)
