### ISSUE TITLE
Does not build in linux 6.13.0

### ISSUE THREAD

**Issue by mvmcmarcos** [tomaspinho/rtl8821ce#356]
I've tried building it through the AUR rtl8821ce-dkms-git package. 

> (2/5) Install DKMS modules
> ==> dkms install --no-depmod rtl8821ce/1.0.5.r172.gf119398 -k 6.6.72-1-lts
> ==> dkms install --no-depmod rtl8821ce/1.0.5.r172.gf119398 -k 6.13.0-2-cachyos
> 
> Error! Bad return status for module build on kernel: 6.13.0-2-cachyos (x86_64)
> Consult /var/lib/dkms/rtl8821ce/1.0.5.r172.gf119398/build/make.log for more information.
> ==> WARNING: `dkms install --no-depmod rtl8821ce/1.0.5.r172.gf119398 -k 6.13.0-2-cachyos' exited 10
> 

Full make.log is attached.

[make.log](https://github.com/user-attachments/files/18514109/make.log)

**Comment by kirisaki-vk** [comment]
Same thing here

 ```
os_dep/linux/ioctl_cfg80211.c:9674:25: error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *)' with an expression of type 'int (struct wiphy *, struct cfg80211_chan_def *)' [-Wincompatible-function-pointer-types]
```

I've also builded it from the aur

**Comment by Spixmaster** [comment]
Is the shipped driver working without flaws?

**Comment by mvmcmarcos** [comment]
> Does the shipped driver work without flaws?

My laptop drops connection every few minutes with the in-kernel rtw driver.

**Comment by dubhater** [comment]
@mvmcmarcos Is it the same with this one? https://github.com/lwfinger/rtw88/

**Comment by Spixmaster** [comment]
The last time I tried that one, it did not work at all. It caused several serious problems.

**Comment by loqs** [comment]
Has anyone affected tried applying a patch based on https://github.com/aircrack-ng/rtl8812au/pull/1220? Such as
```patch
diff --git a/os_dep/linux/ioctl_cfg80211.c b/os_dep/linux/ioctl_cfg80211.c
index d91bbbb..017661b 100644
--- a/os_dep/linux/ioctl_cfg80211.c
+++ b/os_dep/linux/ioctl_cfg80211.c
@@ -5868,7 +5868,10 @@ static int	cfg80211_rtw_set_channel(struct wiphy *wiphy
 }
 
 static int cfg80211_rtw_set_monitor_channel(struct wiphy *wiphy
-#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 8, 0))
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 13, 0))
+	, struct net_device *dev
+	, struct cfg80211_chan_def *chandef
+#elif (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 8, 0))
 	, struct cfg80211_chan_def *chandef
 #else
 	, struct ieee80211_channel *chan
```

**Comment by mvmcmarcos** [comment]
> [@mvmcmarcos](https://github.com/mvmcmarcos) Is it the same with this one? https://github.com/lwfinger/rtw88/

@dubhater it is definitely more stable connection than the current in-kernel driver, but seems to be less stable than this, maybe that is placebo. Thanks for the recommendation anyway. Given rtw88 is always up to date with the kernel releases, I'll stick with that one for now.

**Comment by dubhater** [comment]
@Spixmaster If you report the problems maybe we can fix them.

**Comment by Spixmaster** [comment]
I removed the entry `blacklist rtw88_8821ce` from file "/etc/modprobe.d/blacklist.conf" and uninstalled this driver. The built-in driver seems to work for me without issues in my current environment for some minutes.

Maybe you should give it a try too.

**Comment by sanjarbek-ismatov** [comment]
Wifi fluctuates in the built-in driver when downloading or uploading things. But otherwise, it is fine. I tried to turn off wifi power saving, it seems kind of helped, but not seamlessly.

**Comment by Spixmaster** [comment]
This is a potential pull request.
