### ISSUE TITLE
Failed to compile on 5.1.0

### ISSUE THREAD

**Issue by hashlib** [tomaspinho/rtl8821ce#30]
Failed to compile on 5.1.0 kernel.
`rtl8821ce/os_dep/osdep_service.c:2088:10: error: implicit declaration of function ‘get_ds’; did you mean ‘get_da’? [-Werror=implicit-function-declaration]
   set_fs(get_ds());
`

`
rtl8821ce/os_dep/osdep_service.c:2088:10: error: incompatible type for argument 1 of ‘set_fs’
   set_fs(get_ds());
`

**Comment by acowley** [comment]
Perhaps fallout from [this kernel tree commit](https://github.com/torvalds/linux/commit/736706bee3298208343a76096370e4f6a5c55915).

**Comment by tomaspinho** [comment]
Please check if https://github.com/tomaspinho/rtl8821ce/pull/31 solves the problem for you. Couldn't build against 5.1 to test.

**Comment by hashlib** [comment]
The #31 solves this compilation problem. Thank you!
