### ISSUE TITLE
Error! Bad return status for module build on kernel: 4.18.0-348.20.1.el8_5.x86_64 (x86_64)

### ISSUE THREAD

**Issue by q-gammasig-88** [tomaspinho/rtl8821ce#264]
[carter@djoser rtl8821ce]$ uname -r
4.18.0-348.20.1.el8_5.x86_64

I am getting this error....I made changes to remove access_ok first parameter as mentioned in and older post and changed 4,19 to 4,18 .....any help would be greatly appreciated.
[make.log](https://github.com/tomaspinho/rtl8821ce/files/8328394/make.log)

carter@djoser rtl8821ce]$ sudo ./dkms-install.sh 
About to run dkms install steps...
Creating symlink /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/source -> /usr/src/rtl8821ce-v5.5.2_34066.20200325

Building module:
cleaning build area...
'make' -j8 KVER=4.18.0-348.20.1.el8_5.x86_64.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-348.20.1.el8_5.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.

Building module:
cleaning build area...
'make' -j8 KVER=4.18.0-348.20.1.el8_5.x86_64.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-348.20.1.el8_5.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.
Finished running dkms install steps.

**Comment by q-gammasig-88** [comment]
This looks to be the issue

#define IEEE80211_MAX_AMPDU_BUF  0x100

  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/hal/hal_intf.o
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/os_dep/linux/ioctl_cfg80211.c:9653:3: error: ‘struct cfg80211_ops’ has no member named ‘mgmt_frame_register’
  .mgmt_frame_register = cfg80211_rtw_mgmt_frame_register,
   ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/os_dep/linux/ioctl_cfg80211.c:9653:25: warning: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, u64)’ {aka ‘int (*)(struct wiphy *, struct wireless_dev *, long long unsigned int)’} from incompatible pointer type ‘void (*)(struct wiphy *, struct wireless_dev *, u16,  bool)’ {aka ‘void (*)(struct wiphy *, struct wireless_dev *, short unsigned int,  _Bool)’} [-Wincompatible-pointer-types]
  .mgmt_frame_register = cfg80211_rtw_mgmt_frame_register,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/os_dep/linux/ioctl_cfg80211.c:9653:25: note: (near initialization for ‘rtw_cfg80211_ops.mgmt_tx_cancel_wait’

**Comment by tomaspinho** [comment]
I would refrain from using kernels heavily modified by distributions, such as what CentOS is known to do with their kernels. No support will be given for these as per README. 4.18 is also particularly old, I would consider using a more recent kernel.
