### ISSUE TITLE
Does not seem to compile with gcc 9.2.0

### ISSUE THREAD

**Issue by Strit** [tomaspinho/rtl8821ce#87]
I'm running with this driver on my Manjaro laptop, where we just got gcc 9.2 in the repo.

After that, the DKMS AUR package fails to compile the module for all kernels.
Reverting back to GCC 9.1 makes it compile fine again.

**Comment by Strit** [comment]
Is the make.log something that gets made by DKMS and where does it put it, when it's done building?

**Comment by tomaspinho** [comment]
Well, it looks but it might be best if you just run `make` inside this repo's folder and post the output here.

**Comment by Strit** [comment]
Hm. Seems the issue is not with 9.2, because I also have the issue with 9.1.
but I do have the issue when building the modules for kernel 5.3.5 and 5.4-rc2. When installing the package, from your git, I just get this output:
```
(1/2) Install DKMS modules
==> dkms install rtl8821ce/1.0.0.r65.g55b90f4 -k 4.19.78-1-MANJARO
==> dkms install rtl8821ce/1.0.0.r65.g55b90f4 -k 5.3.5-1-MANJARO
Error! Bad return status for module build on kernel: 5.3.5-1-MANJARO (x86_64)
Consult /var/lib/dkms/rtl8821ce/1.0.0.r65.g55b90f4/build/make.log for more information.
==> dkms install rtl8821ce/1.0.0.r65.g55b90f4 -k 5.4.0-1-MANJARO
Error! Bad return status for module build on kernel: 5.4.0-1-MANJARO (x86_64)
Consult /var/lib/dkms/rtl8821ce/1.0.0.r65.g55b90f4/build/make.log for more information.
```
So as you can see, building it for 4.19 works, but not for 5.3 and 5.4.

**Comment by tomaspinho** [comment]
You're getting a lot of gcc/plugin errors related to mismatched versions of packages. Not sure if the problem is the driver's because no actual compilation errors are shown on the log you posted.

**Comment by Strit** [comment]
Thanks. Tried removing the package along with it's dependencies. Updated GCC to 9.2, then reinstalled the driver package, the reinstalled the 5.3 kernel. This made the dkms module build as it's suppose to.

Confirmed bu rebooting to new kernel and I have wifi again.

Thanks for helping.
