### ISSUE TITLE
Compilation Error on Linux 5.0.0-16

### ISSUE THREAD

**Issue by mnesarco** [tomaspinho/rtl8821ce#45]
This is working with 4.18 but with 5.0 fails:

```
/var/lib/dkms/rtl8821ce/v5.2.5_1.26055.20180108.1/build/os_dep/linux/os_intfs.c:1195:5: error: expected declaration specifiers or ‘...’ before ‘,’ token
     , struct net_device *sb_dev
     ^
/var/lib/dkms/rtl8821ce/v5.2.5_1.26055.20180108.1/build/os_dep/linux/os_intfs.c:1334:22: error: ‘rtw_select_queue’ undeclared here (not in a function); did you mean ‘rtw_recv_select_queue’?
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
                      rtw_recv_select_queue


Makefile:1605: recipe for target '_module_/var/lib/dkms/rtl8821ce/v5.2.5_1.26055.20180108.1/build' failed
make[1]: *** [_module_/var/lib/dkms/rtl8821ce/v5.2.5_1.26055.20180108.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-16-generic'
Makefile:1902: recipe for target 'modules' failed
make: *** [modules] Error 2
```

**Comment by tomaspinho** [comment]
This has been fixed. Update your your installation of the driver.
