### ISSUE TITLE
Driver does not work with Linux 5.19.2

### ISSUE THREAD

**Issue by Spixmaster** [tomaspinho/rtl8821ce#289]
There are several compilation issues. Besides that, I tried the built in driver in the Linux kernel which still does not work. The connection is not established.

```sh
❯ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.19.2-arch1-1/build M=/home/matheus/rtl8821ce  modules
make[1]: Entering directory '/usr/lib/modules/5.19.2-arch1-1/build'
  CC [M]  /home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.o
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_ch_switch_notify':
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:420:9: error: too few arguments to function 'cfg80211_ch_switch_notify'
  420 |         cfg80211_ch_switch_notify(adapter->pnetdev, &chdef);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matheus/rtl8821ce/include/osdep_service_linux.h:93,
                 from /home/matheus/rtl8821ce/include/osdep_service.h:50,
                 from /home/matheus/rtl8821ce/include/drv_types.h:27,
                 from /home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:17:
./include/net/cfg80211.h:7967:6: note: declared here
 7967 | void cfg80211_ch_switch_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c: In function 'cfg80211_rtw_scan':
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:2881:33: warning: the comparison will always evaluate as 'true' for the address of 'ssid' will never be NULL [-Waddress]
 2881 |                 if (ssids->ssid != NULL
      |                                 ^~
./include/net/cfg80211.h:2302:12: note: 'ssid' declared here
 2302 |         u8 ssid[IEEE80211_MAX_SSID_LEN];
      |            ^~~~
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c: At top level:
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9593:20: error: initialization of 'int (*)(struct wiphy *, struct net_device *, unsigned int)' from incompatible pointer type 'int (*)(struct wiphy *, struct net_device *)' [-Werror=incompatible-pointer-types]
 9593 |         .stop_ap = cfg80211_rtw_stop_ap,
      |                    ^~~~~~~~~~~~~~~~~~~~
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9593:20: note: (near initialization for 'rtw_cfg80211_ops.stop_ap')
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_wdev_unregister':
/home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9862:17: error: 'struct wireless_dev' has no member named 'current_bss'
 9862 |         if (wdev->current_bss) {
      |                 ^~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:249: /home/matheus/rtl8821ce/os_dep/linux/ioctl_cfg80211.o] Error 1
make[1]: *** [Makefile:1849: /home/matheus/rtl8821ce] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.19.2-arch1-1/build'
make: *** [Makefile:2244: modules] Error 2
```

**Comment by urparvezali** [comment]
same case with me in the kernel version 5.19.2-arch1-1

**Comment by mmrzax** [comment]
same here

**Comment by loqs** [comment]
If someone is feeling adventurous they could try the patch from https://github.com/loqs/rtl8821ce-dkms-git/blob/master/rtl8821ce-5.19.2.patch which is build tested only based on a request in https://bbs.archlinux.org/viewtopic.php?id=278991

**Comment by Spixmaster** [comment]
> If someone is feeling adventurous they could try the patch from https://github.com/loqs/rtl8821ce-dkms-git/blob/master/rtl8821ce-5.19.2.patch which is build tested only based on a request in https://bbs.archlinux.org/viewtopic.php?id=278991

Don't you want to create a pull request?

**Comment by loqs** [comment]
Not as it is untested.

**Comment by Spixmaster** [comment]
> Not as it is untested.

I just installed it with your patch and it works for me.

**Comment by holyspiritomb** [comment]
> If someone is feeling adventurous they could try the patch from https://github.com/loqs/rtl8821ce-dkms-git/blob/master/rtl8821ce-5.19.2.patch which is build tested only based on a request in https://bbs.archlinux.org/viewtopic.php?id=278991

I am adventurous and it did indeed install and work for me with linux-amd-raven 5.19.2

**Comment by Spixmaster** [comment]
@tomaspinho Could you take a look at #291?

**Comment by gaude** [comment]
@loqs Just installed and working under 5.19.3-arch1-1 
Intel dual core Intel Core i3-813OU
HP Pavilion laptop
Manly thanks for your work

**Comment by urparvezali** [comment]
@loqs it worked & thnk to you

**Comment by younesbourakadi** [comment]
Working here on 5.19.3-arch1-1 
Cheers!!
